FORMAT: 1A
HOST: https://private-58b9e3-devsummittest.apiary-mock.com

# devsummit

description

## User Auth [/auth]

### Register a user [POST /auth/register]

+ Request (application/json)

    + Attributes (object)
        + data (object)
            - attributes (User)

+ Response 200 (application/json)
    + Attributes
        + meta 
            - message: `User succesfully registered`
            - success: true
        + data (UserResponse) 



## User Management [/api/users]

### List of Users [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        + meta (object)
            - count: 10,
            - total: 10
        + data (array[UserResponse]) 


### Get a User [GET /api/users/{user_id}]

+ Parameters

    - user_id: `1` (string, required) - Valid User ID

+ Response 200 (application/json)
    + Attributes
        + meta (object)
            - count: 1,
            - total: 1
        + data (UserResponse) 


### Update a User [PATCH /api/users/{user_id}]

    
+ Parameters
    - user_id : `1` (string, required) - Valid User ID

+ Request (application/json)

    + Headers

            Accept: application/json
            Authorization: Bearer 489312748932748932784732984732

    + Attributes
        + data (object)
            - attributes (User)

+ Response 200 (application/json)
    + Attributes
        + meta (object)
            - message: 'User succesfully updated'
            - success: true
        + data (UserResponse)

 

## Data Structures

###  User
- `first_name`: `andy` (string),
- `last_name`: `herman` (string),
- `username`: `andy` (string),
- `email`: `shi88.andy@gmail.com` (string),
- `created_at`: `Wed, 02 Aug 2017 15:18:31 GMT` (string),
- `updated_at`: `Wed, 02 Aug 2017 15:18:31 GMT` (string)

### UserResponse
- type: 'User' (string)
- id: 1 (number)
- attributes (User)
