FORMAT: 1A
HOST: https://private-909ac-devsummit.apiary-mock.com

# devsummit

Dev summit API blueprints

## Orders [/orders]

### Order a Ticket [POST]

+ Request (application/json)

    + Header
                
                Accept: application/json
                Authorization: Bearer 28391749832174983274019

    + Attributes
        + data (OrderRequest)



## Data Structures

###  User
- `first_name`: `andy` (string),
- `last_name`: `herman` (string),
- `username`: `andy` (string),
- `email`: `shi88.andy@gmail.com` (string),
- `created_at`: `Wed, 02 Aug 2017 15:18:31 GMT` (string),
- `updated_at`: `Wed, 02 Aug 2017 15:18:31 GMT` (string)

### UserResponse
- type: 'User' (string)
- id: 1 (number)
- attributes (User)            

### Ticket
- ticket_type: `gold` (string)
- price: `10000` (number)
- information: `ticket description` (string)

### TicketResponse
- type: `tickets` (string)
- id: `1` (number)
- attributes (Ticket)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Attendee
- feature_code: `123f` (string)
- points: `100` (number)
- summary: `some information about attendee` (string)

### AttendeeResponse
- type: `attendee` (string)
- id: `1` (number)
- attributes (Attendee)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Booth
- points: `100` (number)
- summary: `some information about booth` (string)

### BoothResponse
- type: `booth` (string)
- id: `1` (number)
- attributes (Booth)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Speaker
- summary: `some information about speaker` (string)

### SpeakerResponse
- type: `speaker` (string)
- id: `1` (number)
- attributes (Speaker)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Material
- path: `material/path` (string)

### MaterialResponse
- type: `material` (string)
- id: `1` (number)
- attributes (Material)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Event
- information: `information about the event` (string)
- time_start: `event starting time` (string)
- time_end: `event ending time` (string)

### EventResponse
- type: `event` (string)
- id: `1` (number)
- attributes (Event)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Stage
- stage_type: `stage type` (string)
- information: `information about the stage` (string)

### StageResponse
- type: `stage` (string)
- id: `1` (number)
- attributes (Event)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Beacon
- code: `beacon code` (string)

### BeaconResponse
- type: `beacon` (string)
- id: `1` (number)
- attributes (Beacon)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### Spot
- coordinate_x: `12` (number)
- coordinate_y: `14` (number)

### SpotResponse
- type: `spot` (string)
- id: `1` (number)
- attributes (Spot)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### StagePicture
- url: `image/path` (string)

### StagePictureResponse
- type: `picture` (string)
- id: `1` (number)
- attributes (StagePicture)
    - `created_at`: `2017-06-23 20:27:16` (string, nullable)
    - `updated_at`: `2017-06-23 20:27:16` (string, nullable)

### OrderRequest
- `ticket_id`: 1
