FORMAT: 1A
HOST: :[Gist](data/host.apib)

# devsummit

Dev summit API blueprints


:[Gist](auth.apib)

:[Gist](user.apib)

:[Gist](order.apib)

:[Gist](attendee.apib)

:[Gist](booth.apib)

:[Gist](speaker.apib)

:[Gist](ticket.apib)

:[Gist](material.apib)

:[Gist](event.apib)

:[Gist](stage.apib)

:[Gist](beacon.apib)

:[Gist](spot.apib)







## Data Structures

:[Gist](data/data.apib)