## Tickets [/api/v1/tickets]

### Get list of tickets [GET]

+ Request (application/json)

    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

+ Response 200 (application/json)
    + Attributes (BaseReponse)
        + meta (object)
          - count: `10` (number)
          - total: `10` (number)
        + links (object)
          - first: `https://localhost:5000/api/v1/tickets?page[limit]=10&page[offset]=0` (string, nullable)
          - last: `https://localhost:5000/api/v1/tickets?page[limit]=10&page[offset]=10` (string, nullable)
          - next: `https://localhost:5000/api/v1/tickets?page[limit]=10&page[offset]=10` (string, nullable)
          - prev: `null` (string, nullable)
        + data (array[Ticket])

### Get ticket filter by id [GET /api/v1/tickets/{id}]

+ Request (application/json)

    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

+ Parameters

    - id: `1` (number, required) - valid ticket id

+ Response 200 (application/json)
    + Attributes (BaseReponse)
        + meta (object)
            - message: `Ticket retrieved successfully` (string)
            - success: `true` (boolean)
        + data (array[TicketResponse])

### Edit ticket filter by id [PATCH /api/v1/tickets/{id}]

+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

    + Attributes
        + data (Ticket)

+ Parameters
    
    - id: `1` (number, required) - valid ticket id

+ Response 200 (application/json)

    + Attributes (BaseReponse)
        + meta (object)
            - message:  `Ticket successfully updated` (string)
            - success: `true` (boolean)
        + data (array[TicketResponse])

### Transfer ticket [POST /api/v1/tickets/{ticket_id}/transfer]

+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

    + Attributes
        + data (TicketTransferRequest)

+ Parameters
    
    - ticket_id: `1` (number, required) - valid ticket id

+ Response 200 (application/json)

    + Attributes (BaseReponse)
        + meta (object)
            - message:  `Ticket successfully transfered` (string)
            - success: `true` (boolean)
        + data (TicketResponse)
        + included (object)
            - from (array[UserResponse])
            - to (array[UserResponse])

### Ticket Transfer log [GET /api/v1/tickets/transfer/log]

+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

+ Response 200 (application/json)

    + Attributes (BaseReponse)
        + meta (object)
            - message:  `Ticket transfer log succesfully retrieved` (string)
            - success: `true` (boolean)
        + data (array[TransferTicketLog])
        + included (array)
            - (object)
                - sender (UserResponse)
                - receiver (UserResponse)
        + links (object)
          - first: `https://localhost:5000/api/v1/tickets/transfer/log?page[limit]=10&page[offset]=0` (string, nullable)
          - last: `https://localhost:5000/api/v1/tickets/transfer/log?page[limit]=10&page[offset]=10` (string, nullable)
          - next: `https://localhost:5000/api/v1/tickets/transfer/log?page[limit]=10&page[offset]=10` (string, nullable)
          - prev: `null` (string, nullable)


### Post Ticket [POST /api/v1/tickets]

+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

    + Attributes
        + data (Ticket)

+ Response 200 (application/json)

    + Attributes (BaseReponse)
        + meta (object)
            - message:  `Ticket successfully created` (string)
            - success: `true` (boolean)
        + data (array[TicketResponse])

### Delete ticket [DELETE /api/v1/tickets/{id}]

+ Request (application/json)

    + Headers
    
            Accept: application/json
            Authorization: Bearer :[Gist](data/token.apib)

+ Parameters

    - id: `1` (number, required) - valid ticket id

+ Response 204
